"""empty message

Revision ID: e3e8182650ea
Revises: 550a8118aa5d
Create Date: 2024-01-13 16:15:44.887197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e8182650ea'
down_revision = '550a8118aa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks_owned', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stocks_owned', 'amt_shares',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('stocks_owned', 'stock_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('watchlist_details', 'watchlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watchlist_details', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'watchlist_details', 'watchlists', ['watchlist_id'], ['id'])
    op.alter_column('watchlists', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'watchlists', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlists', type_='unique')
    op.alter_column('watchlists', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'watchlist_details', type_='foreignkey')
    op.alter_column('watchlist_details', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watchlist_details', 'watchlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stocks_owned', 'stock_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('stocks_owned', 'amt_shares',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('stocks_owned', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
